name: CI/CD Pipeline

on:
  push:
    branches: [ main, feature/**, fix/**, release/**, hotfix/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/asyncsite/slack-emoji-service

permissions:
  contents: read
  checks: write
  pull-requests: write
  packages: write

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout slack-emoji-service
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Configure Gradle properties
      run: |
        mkdir -p ~/.gradle
        echo "gpr.user=${{ github.actor }}" >> ~/.gradle/gradle.properties
        echo "gpr.key=${{ secrets.PAT_TOKEN }}" >> ~/.gradle/gradle.properties
        
    - name: Build with Gradle (skip tests)
      run: ./gradlew build -x test --no-daemon --stacktrace
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    
    - name: Run tests
      run: ./gradlew test --no-daemon --stacktrace
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        SPRING_PROFILES_ACTIVE: test
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: '**/build/test-results/test/'
        retention-days: 7
    
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: '**/build/reports/tests/'
        retention-days: 7
    
    - name: Send Discord Notification on Test Failure
      if: failure()
      env:
        STATUS_COLOR: '15158332'
        STATUS_EMOJI: '❌'
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{
               \"embeds\": [{
                 \"title\": \"$STATUS_EMOJI slack-emoji-service 테스트 실패\",
                 \"color\": $STATUS_COLOR,
                 \"fields\": [
                   {\"name\": \"서비스\", \"value\": \"slack-emoji-service\", \"inline\": true},
                   {\"name\": \"브랜치\", \"value\": \"${{ github.ref_name }}\", \"inline\": true},
                   {\"name\": \"실행자\", \"value\": \"${{ github.actor }}\", \"inline\": true},
                   {\"name\": \"커밋\", \"value\": \"\`${GITHUB_SHA::8}\`\", \"inline\": false},
                   {\"name\": \"메시지\", \"value\": \"테스트 단계에서 실패했습니다. 로그를 확인해주세요.\", \"inline\": false},
                   {\"name\": \"시간\", \"value\": \"$(TZ=Asia/Seoul date +'%Y-%m-%d %H:%M:%S KST')\", \"inline\": false}
                 ],
                 \"footer\": {
                   \"text\": \"AsyncSite CI/CD\"
                 },
                 \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\"
               }]
             }" \
             https://discord.com/api/webhooks/1399402822105038999/2qQDazifNKeW_c8MhHqcrw6Li5yDQtBL7f2JIBQ_b4qVT3Vxh7TfpMV3kBFnDYAFL3-h

  build-and-push:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' && 
      github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout slack-emoji-service
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Configure Gradle properties
      run: |
        mkdir -p ~/.gradle
        echo "gpr.user=${{ github.actor }}" >> ~/.gradle/gradle.properties
        echo "gpr.key=${{ secrets.PAT_TOKEN }}" >> ~/.gradle/gradle.properties
    
    - name: Build application
      run: |
        chmod +x gradlew
        ./gradlew build -x test --no-daemon
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{ github.sha }}
    
    - name: Send Discord Notification on Build Failure
      if: failure()
      env:
        STATUS_COLOR: '15158332'
        STATUS_EMOJI: '❌'
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{
               \"embeds\": [{
                 \"title\": \"$STATUS_EMOJI slack-emoji-service 빌드 실패\",
                 \"color\": $STATUS_COLOR,
                 \"fields\": [
                   {\"name\": \"서비스\", \"value\": \"slack-emoji-service\", \"inline\": true},
                   {\"name\": \"브랜치\", \"value\": \"${{ github.ref_name }}\", \"inline\": true},
                   {\"name\": \"실행자\", \"value\": \"${{ github.actor }}\", \"inline\": true},
                   {\"name\": \"커밋\", \"value\": \"\`${GITHUB_SHA::8}\`\", \"inline\": false},
                   {\"name\": \"메시지\", \"value\": \"Docker 이미지 빌드 또는 푸시 단계에서 실패했습니다.\", \"inline\": false},
                   {\"name\": \"시간\", \"value\": \"$(TZ=Asia/Seoul date +'%Y-%m-%d %H:%M:%S KST')\", \"inline\": false}
                 ],
                 \"footer\": {
                   \"text\": \"AsyncSite CI/CD\"
                 },
                 \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\"
               }]
             }" \
             https://discord.com/api/webhooks/1399402822105038999/2qQDazifNKeW_c8MhHqcrw6Li5yDQtBL7f2JIBQ_b4qVT3Vxh7TfpMV3kBFnDYAFL3-h

  deploy:
    name: Deploy to Home Server
    needs: build-and-push
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' && 
      github.ref == 'refs/heads/main'
    
    steps:
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -p 2222 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to server
      run: |
        ssh -p 2222 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'ENDSSH'
          echo "Starting deployment of slack-emoji-service..."
          
          # Navigate to deployment directory
          cd ~/deployments/slack-emoji-service || mkdir -p ~/deployments/slack-emoji-service && cd ~/deployments/slack-emoji-service
          
          # Create docker-compose file
          cat > docker-compose.yml << COMPOSE_EOF
          services:
            slack-emoji-service:
              image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
              container_name: asyncsite-slack-emoji-service
              ports:
                - "13084:13084"
              environment:
                - SPRING_PROFILES_ACTIVE=prod
                - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://asyncsite-eureka:8761/eureka/
                - SPRING_DATASOURCE_URL=jdbc:mysql://asyncsite-mysql:3306/slackemojidb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true&createDatabaseIfNotExist=true
                - SPRING_DATASOURCE_USERNAME=root
                - SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
                - SPRING_DATA_REDIS_HOST=asyncsite-redis
                - SPRING_DATA_REDIS_PORT=6379
                - SPRING_KAFKA_BOOTSTRAP_SERVERS=asyncsite-kafka:9092
                - SLACK_CLIENT_ID=9494654010486.9498856782788
                - SLACK_CLIENT_SECRET=0c0f226daf5a4cf0a74350ef66be791b
                - SLACK_REDIRECT_URI=https://api.asyncsite.com/api/public/slack-emoji/v1/slack/callback
                - JWT_SECRET=${{ secrets.JWT_SECRET }}
              volumes:
                - slack-emoji-service-logs:/app/logs
              networks:
                - asyncsite-network
              logging:
                driver: "json-file"
                options:
                  max-size: "10m"
                  max-file: "5"
              restart: unless-stopped
              healthcheck:
                test: ["CMD", "curl", "-f", "http://localhost:13084/actuator/health"]
                interval: 30s
                timeout: 10s
                retries: 3
                start_period: 60s
          
          networks:
            asyncsite-network:
              external: true
          
          volumes:
            slack-emoji-service-logs:
              driver: local
        COMPOSE_EOF
          
          # Login to GitHub Container Registry
          echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u renechoi --password-stdin
          
          # Pull latest image
          docker pull ${{ env.IMAGE_NAME }}:${{ github.sha }}
          
          # Stop and remove old containers
          docker compose down --remove-orphans || true
          
          # Start new containers
          docker compose up -d
          
          # Wait for services to be healthy
          echo "Waiting for services to be healthy..."
          sleep 45
          
          # Check service status
          docker ps | grep asyncsite-slack-emoji-service
          
          echo "Deployment completed!"
        ENDSSH
    
    - name: Send Discord Notification
      if: always()
      env:
        STATUS_COLOR: ${{ job.status == 'success' && '3066993' || '15158332' }}
        STATUS_EMOJI: ${{ job.status == 'success' && '✅' || '❌' }}
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{
               \"embeds\": [{
                 \"title\": \"$STATUS_EMOJI slack-emoji-service 배포 ${{ job.status }}\",
                 \"color\": $STATUS_COLOR,
                 \"fields\": [
                   {\"name\": \"서비스\", \"value\": \"slack-emoji-service\", \"inline\": true},
                   {\"name\": \"브랜치\", \"value\": \"${{ github.ref_name }}\", \"inline\": true},
                   {\"name\": \"배포자\", \"value\": \"${{ github.actor }}\", \"inline\": true},
                   {\"name\": \"커밋\", \"value\": \"\`${GITHUB_SHA::8}\`\", \"inline\": false},
                   {\"name\": \"시간\", \"value\": \"$(TZ=Asia/Seoul date +'%Y-%m-%d %H:%M:%S KST')\", \"inline\": false}
                 ],
                 \"footer\": {
                   \"text\": \"AsyncSite CI/CD\"
                 },
                 \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\"
               }]
             }" \
             https://discord.com/api/webhooks/1399402822105038999/2qQDazifNKeW_c8MhHqcrw6Li5yDQtBL7f2JIBQ_b4qVT3Vxh7TfpMV3kBFnDYAFL3-h